# Generated by Django 5.2.5 on 2025-08-07 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_location', models.CharField(max_length=100)),
                ('end_location', models.CharField(max_length=100)),
                ('distance', models.FloatField(help_text='Distance in km')),
                ('estimated_duration', models.PositiveIntegerField(help_text='Estimated duration in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.PositiveIntegerField(help_text='Order of station in route')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='api.route')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
