# Generated by Django 5.2.5 on 2025-08-11 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_booking_seats_booked_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='conductor',
            field=models.ForeignKey(blank=True, help_text="User with role 'conductor' who operates this bus", limit_choices_to={'role': 'conductor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bus',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Current latitude of the bus', null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Current longitude of the bus', null=True),
        ),
    ]
